[book]
title = "C++ Journey: Core Principles to Modern Features"
author = "Sagar Kumar Madala"
language = "en"
src = "mds"

[build]
build-dir = "docs"

[output.html]
default-theme = "light"
site-url = "/Cpp_Learn_The_Right_Way/"
git-repository-url = "https://github.com/sagardesd/Cpp_Learn_The_Right_Way"
