[book]
authors = ["Sagar Kumar Madala"]
language = "en"
src = "mds"

[build]
build-dir = "docs"

[output.html]
default-theme = "navy"
additional-css = ["theme/custom.css"]
site-url = "/cpp-ebook-by-sagar/"
