[book]
authors = ["Sagar Kumar Madala"]
language = "en"
src = "cpp11_summary"

[build]
build-dir = "cpp11_docs"

[output.html]
default-theme = "navy"
additional-css = ["theme/custom.css"]
site-url = "/Cpp-ebook/cpp11/"
