[book]
authors = ["Sagar Kumar Madala"]
language = "en"
src = "mds"

[build]
build-dir = "docs"

[output.html]
default-theme = "navy"
no-section-label = false
fold.enable = true
fold.level = 0
site-url = "/cpp-ebook-by-sagar/"
